site_name: Saga Pattern Demo with FastAPI
repo_name: saga-demo
repo_url: https://github.com/as10896/saga-demo
edit_uri: edit/main/docs/
theme:
  name: material
  palette:
    scheme: default
    primary: black
  icon:
    edit: material/pencil
  features:
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Introduction: index.md
  - Saga Flowchart: flowchart.md
