[project]
name = "saga-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "jinja2>=3.1.6",
    "orjson>=3.11.1",
    "redis[hiredis]>=6.3.0",
]
